import { ZsClassMember } from "../../construction/class-declarations/field"
import { ZsOverloads } from "../../construction"
import { tf } from "../tf"
import { MethodDeclaration, ClassDeclaration, ClassElement } from "typescript"
import { zsInspect } from "../zt-types"
